# Generated by Django 4.1.7 on 2023-05-01 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('', 'Aguascalientes'), ('', 'Baja California'), ('', 'Baja California Sur'), ('', 'Campeche'), ('', 'Coahuila'), ('', 'Colima'), ('', 'Chiapas'), ('', 'Chihuahua'), ('', 'Ciudad de México'), ('', 'Durango'), ('', 'Guanajuato'), ('', 'Guerrero'), ('', 'Hidalgo'), ('', 'Jalisco'), ('', 'Estado de México'), ('', 'Michoacán'), ('', 'Morelos'), ('', 'Nayarit'), ('', 'Nuevo León'), ('', 'Oaxaca'), ('', 'Puebla'), ('', 'Querétaro'), ('', 'Quintana Roo'), ('', 'San Luis Potosí'), ('', 'Sinaloa'), ('', 'Sonora'), ('', 'Tabasco'), ('', 'Tamaulipas'), ('', 'Tlaxcala'), ('', 'Veracruz'), ('', 'Yucatán'), ('', 'Zacatecas')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wca_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
