# Generated by Django 4.1.7 on 2023-05-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0002_cubingmexicoprofile_last_edit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubingmexicoprofile',
            name='last_edit_date',
        ),
    ]
