# Generated by Django 4.1.7 on 2023-05-02 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0002_user_created_at_user_state_user_state_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wca_id',
        ),
        migrations.AddField(
            model_name='user',
            name='has_default_password',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WCAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_pk', models.IntegerField()),
                ('wca_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=10)),
                ('country_iso2', models.CharField(max_length=10)),
                ('delegate_status', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar_url', models.CharField(max_length=255)),
                ('avatar_thumb_url', models.CharField(max_length=255)),
                ('is_default_avatar', models.BooleanField()),
                ('wca_created_at', models.CharField(max_length=500)),
                ('wca_updated_at', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CubingmexicoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('', 'Aguascalientes'), ('', 'Baja California'), ('', 'Baja California Sur'), ('', 'Campeche'), ('', 'Coahuila'), ('', 'Colima'), ('', 'Chiapas'), ('', 'Chihuahua'), ('', 'Ciudad de México'), ('', 'Durango'), ('', 'Guanajuato'), ('', 'Guerrero'), ('', 'Hidalgo'), ('', 'Jalisco'), ('', 'Estado de México'), ('', 'Michoacán'), ('', 'Morelos'), ('', 'Nayarit'), ('', 'Nuevo León'), ('', 'Oaxaca'), ('', 'Puebla'), ('', 'Querétaro'), ('', 'Quintana Roo'), ('', 'San Luis Potosí'), ('', 'Sinaloa'), ('', 'Sonora'), ('', 'Tabasco'), ('', 'Tamaulipas'), ('', 'Tlaxcala'), ('', 'Veracruz'), ('', 'Yucatán'), ('', 'Zacatecas')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
