# Generated by Django 4.1.7 on 2023-05-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0006_alter_cubingmexicoprofile_wca_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubingmexicoprofile',
            name='wca_id',
        ),
    ]
