# Generated by Django 4.1.7 on 2023-05-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0007_remove_cubingmexicoprofile_wca_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubingmexicoprofile',
            name='is_state_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='static/img/team_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.state')),
            ],
        ),
        migrations.AddField(
            model_name='cubingmexicoprofile',
            name='state_team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cubingmexico_web.stateteam'),
        ),
    ]
