# Generated by Django 4.1.7 on 2023-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0009_alter_stateteam_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateteam',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stateteam',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
