# Generated by Django 4.1.7 on 2023-05-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0010_stateteam_facebook_link_stateteam_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateteam',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
