# Generated by Django 4.1.7 on 2023-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0011_alter_stateteam_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateteam',
            name='facebook_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
