# Generated by Django 4.1.7 on 2023-05-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0012_alter_stateteam_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateteam',
            options={'permissions': (('edit_stateteam', 'Can edit state team'),)},
        ),
        migrations.CreateModel(
            name='PersonStateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_wca.person')),
                ('state_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.stateteam')),
            ],
        ),
    ]
