# Generated by Django 4.1.7 on 2023-05-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0013_alter_stateteam_options_personstateteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubingmexicoprofile',
            name='state_team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cubingmexico_web.personstateteam'),
        ),
        migrations.AlterUniqueTogether(
            name='personstateteam',
            unique_together={('person', 'state_team')},
        ),
    ]
