# Generated by Django 4.1.7 on 2023-05-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0014_alter_cubingmexicoprofile_state_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cubingmexicoprofile',
            old_name='state_team',
            new_name='person_state_team',
        ),
    ]
