# Generated by Django 4.1.7 on 2023-05-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0015_rename_state_team_cubingmexicoprofile_person_state_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='three_letter_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
