# Generated by Django 4.1.7 on 2023-05-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0017_alter_state_three_letter_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cubingmexicoprofile',
            options={'verbose_name': 'Perfil de Cubingmexico', 'verbose_name_plural': 'Perfiles de Cubingmexico'},
        ),
        migrations.AlterModelOptions(
            name='personstateteam',
            options={'verbose_name': 'Miembro de team', 'verbose_name_plural': 'Miembros de team'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado de la Republica Mexicana', 'verbose_name_plural': 'Estados de la Republica Mexicana'},
        ),
        migrations.AlterModelOptions(
            name='stateteam',
            options={'permissions': (('edit_stateteam', 'Can edit state team'),), 'verbose_name': 'Team estatal', 'verbose_name_plural': 'Teams estatales'},
        ),
        migrations.AlterField(
            model_name='personstateteam',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_wca.person', verbose_name='Persona con WCAID'),
        ),
        migrations.AlterField(
            model_name='personstateteam',
            name='state_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.stateteam', verbose_name='Estado de la Republica Mexicana'),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción del team'),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='facebook_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Enlace de Facebook'),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Enlace de Instagram'),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del team'),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.state', verbose_name='Estado de la Republica Mexicana'),
        ),
        migrations.AlterField(
            model_name='stateteam',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/team_logos/', verbose_name='Logotipo del team'),
        ),
    ]
