# Generated by Django 4.1.7 on 2023-05-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0019_alter_stateteam_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateteam',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.state', verbose_name='Estado de la Republica Mexicana'),
        ),
    ]
