# Generated by Django 4.1.7 on 2023-05-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0020_alter_stateteam_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personstateteam',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_wca.person', verbose_name='Persona con WCAID'),
        ),
    ]
