# Generated by Django 4.1.7 on 2023-08-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0023_stateteam_email_alter_stateteam_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_wca.competition', verbose_name='Competencia oficial')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.state', verbose_name='Estado de la Republica Mexicana')),
            ],
            options={
                'verbose_name': 'Estado de la competencia',
                'verbose_name_plural': 'Estado de las competencias',
                'unique_together': {('competition', 'state')},
            },
        ),
    ]
