# Generated by Django 4.1.7 on 2023-08-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0024_competitionstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionstate',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_wca.competition', verbose_name='Competencia oficial'),
        ),
    ]
