# Generated by Django 4.1.7 on 2023-08-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0026_staterankssingle_stateranksaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateranksaverage',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cubingmexico_web.state'),
        ),
        migrations.AddField(
            model_name='staterankssingle',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cubingmexico_web.state'),
        ),
    ]
