# Generated by Django 4.1.7 on 2023-08-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0027_stateranksaverage_state_staterankssingle_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateranksaverage',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cubingmexico_web.state'),
        ),
        migrations.AlterField(
            model_name='staterankssingle',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cubingmexico_web.state'),
        ),
    ]
