# Generated by Django 4.1.7 on 2023-08-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0028_alter_stateranksaverage_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateranksaverage',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cubingmexico_web.state'),
        ),
        migrations.AlterField(
            model_name='staterankssingle',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cubingmexico_web.state'),
        ),
    ]
