# Generated by Django 4.1.7 on 2023-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0029_alter_stateranksaverage_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateranksaverage',
            name='state',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='staterankssingle',
            name='state',
            field=models.CharField(max_length=3),
        ),
    ]
