# Generated by Django 4.1.7 on 2023-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_web', '0030_alter_stateranksaverage_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del donador')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto donado')),
                ('is_active', models.BooleanField(default=True)),
                ('donation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donador',
                'verbose_name_plural': 'Donadores',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del patrocinador')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción del patrocinador')),
                ('sponsor_logo', models.ImageField(blank=True, null=True, upload_to='img/sponsors/', verbose_name='Logotipo del patrocinador')),
                ('link', models.URLField(blank=True, default='', max_length=255, verbose_name='Enlace de interés')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto donado')),
                ('is_active', models.BooleanField(default=True)),
                ('donation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
    ]
