# Generated by Django 4.1.7 on 2024-03-11 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubingmexico_wca', '0001_initial'),
        ('cubingmexico_web', '0032_alter_sponsor_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, verbose_name='Nombre del equipo')),
                ('members', models.ManyToManyField(to='cubingmexico_wca.person', verbose_name='Miembros del equipo')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubingmexico_web.sponsor', verbose_name='Patrocinador')),
            ],
            options={
                'verbose_name': 'Equipo de Patrocinador',
                'verbose_name_plural': 'Equipos de Patrocinadores',
            },
        ),
    ]
