from django.urls import path

from .views import *

app_name = 'cubingmexico_web'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('person/<str:wca_id>/', MyResultsView.as_view(), name='my_results'),
    path('national_rankings/333/single', NationalRankings333SingleView.as_view(), name='national_rankings_333_single'),
    path('national_rankings/333/average', NationalRankings333AverageView.as_view(), name='national_rankings_333_average'),
    path('national_rankings/222/single', NationalRankings222SingleView.as_view(), name='national_rankings_222_single'),
    path('national_rankings/222/average', NationalRankings222AverageView.as_view(), name='national_rankings_222_average'),
    path('national_rankings/444/single', NationalRankings444SingleView.as_view(), name='national_rankings_444_single'),
    path('national_rankings/444/average', NationalRankings444AverageView.as_view(), name='national_rankings_444_average'),
    path('national_rankings/555/single', NationalRankings555SingleView.as_view(), name='national_rankings_555_single'),
    path('national_rankings/555/average', NationalRankings555AverageView.as_view(), name='national_rankings_555_average'),
    path('national_rankings/666/single', NationalRankings666SingleView.as_view(), name='national_rankings_666_single'),
    path('national_rankings/666/average', NationalRankings666AverageView.as_view(), name='national_rankings_666_average'),
    path('national_rankings/777/single', NationalRankings777SingleView.as_view(), name='national_rankings_777_single'),
    path('national_rankings/777/average', NationalRankings777AverageView.as_view(), name='national_rankings_777_average'),
    path('national_rankings/333bf/single', NationalRankings333bfSingleView.as_view(), name='national_rankings_333bf_single'),
    path('national_rankings/333bf/average', NationalRankings333bfAverageView.as_view(), name='national_rankings_333bf_average'),
    path('national_rankings/333fm/single', NationalRankings333fmSingleView.as_view(), name='national_rankings_333fm_single'),
    path('national_rankings/333fm/average', NationalRankings333fmAverageView.as_view(), name='national_rankings_333fm_average'),
    path('national_rankings/333oh/single', NationalRankings333ohSingleView.as_view(), name='national_rankings_333oh_single'),
    path('national_rankings/333oh/average', NationalRankings333ohAverageView.as_view(), name='national_rankings_333oh_average'),
    path('national_rankings/clock/single', NationalRankingsclockSingleView.as_view(), name='national_rankings_clock_single'),
    path('national_rankings/clock/average', NationalRankingsclockAverageView.as_view(), name='national_rankings_clock_average'),
    path('national_rankings/minx/single', NationalRankingsminxSingleView.as_view(), name='national_rankings_minx_single'),
    path('national_rankings/minx/average', NationalRankingsminxAverageView.as_view(), name='national_rankings_minx_average'),
    path('national_rankings/pyram/single', NationalRankingspyramSingleView.as_view(), name='national_rankings_pyram_single'),
    path('national_rankings/pyram/average', NationalRankingspyramAverageView.as_view(), name='national_rankings_pyram_average'),
    path('national_rankings/skewb/single', NationalRankingsskewbSingleView.as_view(), name='national_rankings_skewb_single'),
    path('national_rankings/skewb/average', NationalRankingsskewbAverageView.as_view(), name='national_rankings_skewb_average'),
    path('national_rankings/sq1/single', NationalRankingssq1SingleView.as_view(), name='national_rankings_sq1_single'),
    path('national_rankings/sq1/average', NationalRankingssq1AverageView.as_view(), name='national_rankings_sq1_average'),
    path('national_rankings/444bf/single', NationalRankings444bfSingleView.as_view(), name='national_rankings_444bf_single'),
    path('national_rankings/444bf/average', NationalRankings444bfAverageView.as_view(), name='national_rankings_444bf_average'),
    path('national_rankings/555bf/single', NationalRankings555bfSingleView.as_view(), name='national_rankings_555bf_single'),
    path('national_rankings/555bf/average', NationalRankings555bfAverageView.as_view(), name='national_rankings_555bf_average'),
    path('national_rankings/333mbf', NationalRankings333mbfView.as_view(), name='national_rankings_333mbf'),
    path('state_rankings/', StateRankingsView.as_view(), name='state_rankings'),
    path('state_records/', StateRecordsView.as_view(), name='state_records'),
    path('state_teams/', StateTeamsView.as_view(), name='state_teams'),
    path('team/<int:pk>/', IndividualStateTeamView.as_view(), name='team'),
    path('team/<int:pk>/edit/', EditStateTeamView.as_view(), name='edit_team'),
    path('unrs/', UNRsView.as_view(), name='unrs'),
    path('cubingmexico_wca/callback/', WCACallbackView.as_view(), name='wca_callback'),
]